Repository Indievelopers/wordle, pull requests merged in 2022-04, with the labels that each got.

#3 Se agrego la documentación inicial del proyecto
  README.md
  docs/images/descargar.jpg
  docs/images/spanish-wordle-how-to-2.jpg
  docs/images/wordle.jpg
Labels: documentation

#5 Se creo la funcion 'randomWord'
  docs/git_steps.md
  requirements.txt
  src/__init__.py
  src/tests/__init__.py
  src/tests/test_utils.py
  src/utils.py
  tox.ini
Labels: documentation, feature

#6 Se creo la función de verificación de la palabra puesta por el usuario
  src/tests/test_utils.py
  src/utils.py
Labels: feature

#10 Added pre-commit configuration for code standard
  .pre-commit-config.yaml
  README.md
  requirements.txt
  src/tests/test_utils.py
  src/utils.py
  tox.ini
Labels: enhancement
